---
AWSTemplateFormatVersion: "2010-09-09"
Description: Provisions the DynamoDB table used to track account provisioning requests

Parameters:
  AccountsTableName:
    Type: String
    Description: The name of the DynamoDB table to create
    Default: lz-aws-accounts
  AccountsTableNameHashKey:
    Type: String
    Description: The name of the hash key for the DynamoDB table
    Default: account_name
  BillingMode:
    Type: String
    Description: The billing mode of the DynamoDB table
    Default: PAY_PER_REQUEST

Resources:
  # Ensure the table is
  # - Created with on-demand billing
  # - Has a hash key of account_name
  # - Is accessible by the account root user
  # - Has tags applied to the table
  # - Is encrypted using AWS managed KMS key

  AccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: !Ref BillingMode
      TableName: !Ref AccountsTableName
      AttributeDefinitions:
        - AttributeName: !Ref AccountsTableNameHashKey
          AttributeType: S
      KeySchema:
        - AttributeName: !Ref AccountsTableNameHashKey
          KeyType: HASH
      ResourcePolicy:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: AllowAccountRoot
              Effect: Allow
              Principal:
                AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
              Action: dynamodb:*
              Resource:
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${AccountsTableName}"
      Tags:
        - Key: Environment
          Value: Production
        - Key: GitRepo
          Value: https://github.com/appvia-lz-aws/lz-aws-bootstrap
        - Key: Owner
          Value: Engineering
        - Key: Product
          Value: LandingZone
        - Key: aws-cloudformation-stack-id
          Value: !Ref "AWS::StackId"
        - Key: aws-cloudformation-stack-name
          Value: !Ref "AWS::StackName"
      SSESpecification:
        SSEEnabled: true
