---
AWSTemplateFormatVersion: "2010-09-09"
Description: Provisions the identity provider in member account

Parameters:
  ClientIdList:
    Type: CommaDelimitedList
    Description: The list of Client IDs to trust
  ThumbprintList:
    Type: CommaDelimitedList
    Description: The list of thumbprints to trust
  IdentityProviderName:
    Type: String
    Description: The name of the OIDC Identity Provider

Resources:
  IdentityProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList: !Ref ClientIdList
      Tags:
%{ for key, value in tags ~}
        - Key: ${key}
          Value: ${value}
%{ endfor ~}
        - Key: aws-cloudformation-stack-id
          Value: !Ref "AWS::StackId"
        - Key: aws-cloudformation-stack-name
          Value: !Ref "AWS::StackName"
      ThumbprintList: !Ref ThumbprintList
      Url: !Sub https://$${IdentityProviderName}
