---
AWSTemplateFormatVersion: "2010-09-09"
Description: Create an S3 Bucket and DynamoDB Table for Terraform Remote State

Parameters:
  Environment:
    Type: String
    Description: The name of the environment
    Default: Production
  GitRepo:
    Type: String
    Description: The URL of the Git repository
  Owner:
    Type: String
    Description: The desiginated owner of the resources
  Product:
    Type: String
    Description: The desiginated product name

Resources:
  TerraformStateS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-${AWS::Region}-tfstate"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteNonCurrentVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: GitRepo
          Value: !Ref GitRepo
        - Key: Owner
          Value: !Ref Owner
        - Key: Provisioner
          Value: CloudFormation
        - Key: Product
          Value: !Ref Product
        - Key: aws-cloudformation-stack-id
          Value: !Ref "AWS::StackId"
        - Key: aws-cloudformation-stack-name
          Value: !Ref "AWS::StackName"

  TerraformStateLockDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
      TableName: !Sub "${AWS::AccountId}-${AWS::Region}-tflock"
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: GitRepo
          Value: !Ref GitRepo
        - Key: Owner
          Value: !Ref Owner
        - Key: Product
          Value: !Ref Product
        - Key: Provisioner
          Value: CloudFormation
        - Key: aws-cloudformation-stack-id
          Value: !Ref "AWS::StackId"
        - Key: aws-cloudformation-stack-name
          Value: !Ref "AWS::StackName"
