---
AWSTemplateFormatVersion: "2010-09-09"
Description: Create an S3 Bucket for Terraform Remote State

Resources:
  TerraformStateS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "$${AWS::AccountId}-$${AWS::Region}-tfstate"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteNonCurrentVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      Tags:
%{ for key, value in tags ~}
        - Key: ${key}
          Value: ${value}
%{ endfor ~}
        - Key: Name 
          Value: !Sub "$${AWS::AccountId}-$${AWS::Region}-tfstate"
        - Key: aws-cloudformation-stack-id
          Value: !Ref "AWS::StackId"
        - Key: aws-cloudformation-stack-name
          Value: !Ref "AWS::StackName"
